import { useEffect, useState } from "react";
import { getCSRFToken } from "../../utils/csrf";

export default function AssessmentModal({ jobId, open, onClose, mode = "assessment" }) {
  const [data, setData] = useState({ parts: [], labours: [], job_no: "" });
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  useEffect(() => { if (!open || !jobId) return; fetch(`/api/jobcard/${jobId}/assessment/?t=${Date.now()}`, { credentials: "same-origin" }).then((r) => r.json()).then(setData).catch(() => setError("Unable to load assessment.")); }, [open, jobId]);
  if (!open) return null;
  const update = (type, index, key, value) => setData((current) => ({ ...current, [type]: current[type].map((row, i) => i === index ? { ...row, [key]: value } : row) }));
  const save = async () => { setSaving(true); setError(""); try { const response = await fetch(`/api/jobcard/${jobId}/assessment/save/`, { method: "POST", credentials: "same-origin", headers: { "Content-Type": "application/json", "X-CSRFToken": getCSRFToken() }, body: JSON.stringify(data) }); const result = await response.json(); if (!response.ok || result.status !== "success") throw new Error(result.message || "Unable to save assessment."); onClose(); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  const table = (title, type, rows) => <section className="assessment-react-table"><h3>{title}</h3><table><thead><tr><th>Code</th><th>Description</th><th>Amount</th><th>Decision</th><th>Revised</th></tr></thead><tbody>{rows.length ? rows.map((row, i) => <tr key={row.id || i}><td>{row.part_no || row.job_code || "-"}</td><td>{row.description || "-"}</td><td>{row.amount || "0"}</td><td><select value={row.decision || "None"} onChange={(e) => update(type, i, "decision", e.target.value)}><option>None</option><option>New</option><option>Repair</option><option>Approved</option><option>Rejected</option></select></td><td><input type="number" value={row.revised_amount ?? row.amount ?? "0"} onChange={(e) => update(type, i, "revised_amount", e.target.value)} /></td></tr>) : <tr><td colSpan="5">No entries found.</td></tr>}</tbody></table></section>;
  return <div className="assessment-react-backdrop" onMouseDown={(e) => e.target === e.currentTarget && onClose()}><div className="assessment-react-modal"><header><div><span>INSURANCE WORKFLOW</span><h2>{mode === "paid-job" ? "Paid Job Assessment" : "Insurance Assessment"}</h2></div><button type="button" onClick={onClose}>×</button></header>{error && <p className="assessment-react-error">{error}</p>}<div className="assessment-react-grid">{table("Parts Assessment", "parts", data.parts)}{table("Labour Assessment", "labours", data.labours)}</div><footer><button type="button" onClick={() => window.open(`/jobCard/${jobId}/assessment-print/`, "_blank")}>Print Assessment</button><button type="button" onClick={save} disabled={saving}>{saving ? "Saving..." : "Save Assessment"}</button></footer></div></div>;
}
