# Generated by Django 6.0.4 on 2026-05-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ins_co_name', models.CharField(max_length=255)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=6, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_no', models.CharField(blank=True, max_length=14, null=True)),
                ('cashless', models.BooleanField(default=False)),
                ('claim_manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('moa_date', models.DateField(blank=True, null=True)),
                ('net_moa_date', models.DateField(blank=True, null=True)),
                ('dms_code', models.CharField(blank=True, max_length=20, null=True)),
                ('customer_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
