# Generated by Django 6.0.4 on 2026-05-04 16:20

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_insurancecompany'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancecompany',
            options={'ordering': ['ins_co_name']},
        ),
        migrations.AddField(
            model_name='insurancecompany',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='gst_no',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^[0-9A-Z]{15}$', 'Enter valid GSTIN')]),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter valid 10 digit mobile number')]),
        ),
        migrations.AlterField(
            model_name='insurancecompany',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter valid 6 digit PIN code')]),
        ),
        migrations.AddIndex(
            model_name='insurancecompany',
            index=models.Index(fields=['ins_co_name'], name='core_insura_ins_co__068338_idx'),
        ),
        migrations.AddIndex(
            model_name='insurancecompany',
            index=models.Index(fields=['city'], name='core_insura_city_9df191_idx'),
        ),
        migrations.AddConstraint(
            model_name='insurancecompany',
            constraint=models.UniqueConstraint(fields=('ins_co_name', 'branch'), name='unique_company_branch'),
        ),
    ]
