# Generated by Django 6.0.4 on 2026-05-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_customer_mobile_no'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_name_mobile',
        ),
    ]
