# Generated by Django 6.0.4 on 2026-05-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_customer_mobile_no'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('name', 'mobile_no'), name='unique_customer_name_mobile'),
        ),
    ]
