# Generated by Django 6.0.4 on 2026-05-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_columnpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('license_no', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='itemdata',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='itemdata',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
