# Generated by Django 6.0.4 on 2026-05-06 16:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_surveyor_alter_itemdata_price_alter_itemdata_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyor',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter valid 10 digit mobile number')]),
        ),
    ]
