# Generated by Django 6.0.4 on 2026-05-07 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_no', models.CharField(max_length=30, unique=True)),
                ('accident_date', models.DateField()),
                ('intimation_date', models.DateField(auto_now_add=True)),
                ('estimated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('INSPECTION', 'Inspection'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('INVOICED', 'Invoiced'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('insurance_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.insurancecompany')),
                ('surveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.surveyor')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicle')),
            ],
        ),
    ]
