# Generated by Django 6.0.4 on 2026-05-07 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_claim'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='claim',
            name='assigned_employee',
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_stage',
            field=models.CharField(choices=[('Created', 'Created'), ('Survey Pending', 'Survey Pending'), ('Estimate Pending', 'Estimate Pending'), ('Approval Pending', 'Approval Pending'), ('Repair Running', 'Repair Running'), ('Ready Delivery', 'Ready Delivery'), ('Delivered', 'Delivered'), ('Closed', 'Closed')], default='Created', max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('Cashless', 'Cashless'), ('Reimbursement', 'Reimbursement')], default='Cashless', max_length=30),
        ),
        migrations.AddField(
            model_name='claim',
            name='fuel_level',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='gate_in_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gate In Time'),
        ),
        migrations.AddField(
            model_name='claim',
            name='ic_claim_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Insurance Claim No'),
        ),
        migrations.AddField(
            model_name='claim',
            name='km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Current KM'),
        ),
        migrations.AddField(
            model_name='claim',
            name='part_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='part_order_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='claim',
            name='part_order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Placed', 'Order Placed'), ('In Transit', 'In Transit'), ('Partially Received', 'Partially Received'), ('Back Order', 'Back Order'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='claim',
            name='policy_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='survey_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='survey_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Re-Inspection', 'Re-Inspection')], default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='claim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='vehicle_inward_type',
            field=models.CharField(choices=[('Pickup', 'Pickup'), ('Walk-in', 'Walk-in'), ('Breakdown', 'Breakdown')], default='Walk-in', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='accident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='approved_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_no',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.customer'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='estimated_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='claim',
            name='insurance_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.insurancecompany'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='intimation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Open', max_length=30),
        ),
        migrations.AlterField(
            model_name='claim',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.vehicle'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_no'], name='core_claim_claim_n_faa106_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status'], name='core_claim_status_f676c8_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['claim_stage'], name='core_claim_claim_s_b951f0_idx'),
        ),
    ]
