# Generated by Django 6.0.4 on 2026-05-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_claim_options_remove_claim_assigned_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='fuel_level',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='gate_in_datetime',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='km',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='vehicle_inward_type',
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=30, unique=True)),
                ('job_date', models.DateField(auto_now_add=True)),
                ('vehicle_inward_type', models.CharField(choices=[('Pickup', 'Pickup'), ('Walk-in', 'Walk-in'), ('Breakdown', 'Breakdown')], default='Walk-in', max_length=20)),
                ('vehicle_inward_by', models.CharField(blank=True, max_length=20)),
                ('gate_in_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Gate In Time')),
                ('expected_delivery_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Actual PromisedDelivery Date')),
                ('km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Current KM')),
                ('fuel_level', models.CharField(blank=True, max_length=20)),
                ('bay_no', models.CharField(blank=True, max_length=20)),
                ('repair_status', models.CharField(choices=[('Pending', 'Pending'), ('Started', 'Started'), ('Under Repair', 'Under Repair'), ('Paint', 'Paint'), ('Assembly', 'Assembly'), ('QC', 'QC'), ('Completed', 'Completed')], default='Pending', max_length=30)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('actual_delivery', models.DateTimeField(blank=True, null=True)),
                ('repair_instructions', models.TextField(blank=True)),
                ('qc_done', models.BooleanField(default=False)),
                ('road_test_done', models.BooleanField(default=False)),
                ('washing_done', models.BooleanField(default=False)),
                ('ready_for_delivery', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisor_jobs', to='core.employee')),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.claim')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_jobs', to='core.employee')),
            ],
        ),
    ]
