# Generated by Django 6.0.4 on 2026-05-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_claim_fuel_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='part_order_date',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='part_order_no',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='part_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='part_order_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
