# Generated by Django 6.0.4 on 2026-05-07 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_claim_part_order_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='part_order_status',
        ),
        migrations.AddField(
            model_name='jobcard',
            name='part_order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Order Placed', 'Order Placed'), ('In Transit', 'In Transit'), ('Partially Received', 'Partially Received'), ('Back Order', 'Back Order'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_stage',
            field=models.CharField(choices=[('Vehicle Inward', 'Vehicle Inward'), ('Claim Created', 'Claim Created'), ('Survey Pending', 'Survey Pending'), ('Survey Completed', 'Survey Completed'), ('Estimate Pending', 'Estimate Pending'), ('Approval Pending', 'Approval Pending'), ('Approval Received', 'Approval Received'), ('Repair Running', 'Repair Running'), ('Painting', 'Painting'), ('QC', 'QC'), ('Billing', 'Billing'), ('Ready Delivery', 'Ready Delivery'), ('Delivered', 'Delivered'), ('Closed', 'Closed')], default='Claim Created', max_length=50),
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='claims/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.claim')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.claim')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='claim_photos/')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.claim')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='core.claim')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobLabour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_code', models.CharField(max_length=200)),
                ('labour_name', models.CharField(max_length=200)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labours', to='core.jobcard')),
            ],
        ),
    ]
