# Generated by Django 6.0.4 on 2026-05-09 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_claim_part_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='customer',
        ),
        migrations.AddField(
            model_name='claim',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.employee'),
        ),
    ]
