# Generated by Django 6.0.4 on 2026-05-09 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_claim_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='insurance_company',
            new_name='insurancecompany',
        ),
        migrations.AlterField(
            model_name='claim',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_stage',
            field=models.CharField(blank=True, choices=[('Vehicle Inward', 'Vehicle Inward'), ('Claim Created', 'Claim Created'), ('Survey Pending', 'Survey Pending'), ('Survey Completed', 'Survey Completed'), ('Estimate Pending', 'Estimate Pending'), ('Approval Pending', 'Approval Pending'), ('Approval Received', 'Approval Received'), ('Repair Running', 'Repair Running'), ('Painting', 'Painting'), ('QC', 'QC'), ('Billing', 'Billing'), ('Ready Delivery', 'Ready Delivery'), ('Delivered', 'Delivered'), ('Closed', 'Closed')], default='Claim Created', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='estimated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='survey_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Re-Inspection', 'Re-Inspection')], default='Pending', max_length=30, null=True),
        ),
    ]
