# Generated by Django 6.0.4 on 2026-05-09 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_rename_insurance_company_claim_insurancecompany_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='insurancecompany',
            new_name='insurance_company',
        ),
    ]
