# Generated by Django 6.0.4 on 2026-05-10 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_employee_user_alter_claim_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_stage',
            field=models.IntegerField(choices=[(1, 'Claim Created'), (2, 'Advisor Assigned'), (3, 'Estimate Created'), (4, 'Claim Intimation'), (5, 'Survey'), (6, 'Insurance Approval'), (7, 'Repair Completed'), (8, 'Closed')], default=1),
        ),
    ]
