# Generated by Django 6.0.4 on 2026-05-10 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_claim_claim_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='bay_no',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='jobcard',
            name='technician',
        ),
        migrations.CreateModel(
            name='JobCardLabour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('labour_hrs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labours', to='core.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='JobCardPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.jobcard')),
            ],
        ),
        migrations.DeleteModel(
            name='JobLabour',
        ),
    ]
