# Generated by Django 6.0.4 on 2026-05-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_jobcard_bay_no_remove_jobcard_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='jobcard',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='labour_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='parts_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
