# Generated by Django 6.0.4 on 2026-05-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_companysetup'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='assessment_file',
            field=models.FileField(blank=True, null=True, upload_to='claim_assessments/'),
        ),
        migrations.AddField(
            model_name='claim',
            name='insurance_approval_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='insurance_note',
            field=models.TextField(blank=True),
        ),
    ]
