# Generated by Django 6.0.4 on 2026-05-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_claim_assessment_file_claim_insurance_approval_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdata',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='itemdata',
            name='item_no',
        ),
        migrations.RemoveField(
            model_name='itemdata',
            name='price',
        ),
        migrations.RemoveField(
            model_name='itemdata',
            name='qty',
        ),
        migrations.RemoveField(
            model_name='itemdata',
            name='user',
        ),
        migrations.AddField(
            model_name='itemdata',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itemdata',
            name='item_code',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemdata',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itemdata',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='itemdata',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
    ]
