# Generated by Django 6.0.4 on 2026-05-14 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_itemdata_created_at_remove_itemdata_item_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardAssessmentLabour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('New', 'New'), ('Repair', 'Repair'), ('KO', 'KO'), ('None', 'None')], default='None', max_length=20)),
                ('revised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_labours', to='core.jobcard')),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobcardlabour')),
            ],
        ),
        migrations.CreateModel(
            name='JobCardAssessmentPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('New', 'New'), ('Repair', 'Repair'), ('KO', 'KO'), ('None', 'None')], default='None', max_length=20)),
                ('revised_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_parts', to='core.jobcard')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobcardpart')),
            ],
        ),
    ]
