# Generated by Django 6.0.4 on 2026-05-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_jobcardassessmentlabour_jobcardassessmentpart'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spare_wheel', models.BooleanField(default=False)),
                ('jack', models.BooleanField(default=False)),
                ('tool_kit', models.BooleanField(default=False)),
                ('floor_mat', models.BooleanField(default=False)),
                ('mud_flap', models.BooleanField(default=False)),
                ('stereo', models.BooleanField(default=False)),
                ('battery', models.BooleanField(default=False)),
                ('wheel_cap', models.BooleanField(default=False)),
                ('number_plate', models.BooleanField(default=False)),
                ('fuel_percent', models.PositiveIntegerField(default=0)),
                ('cng_percent', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='core.jobcard')),
            ],
        ),
    ]
