# Generated by Django 6.0.4 on 2026-05-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_jobcardinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardinventory',
            name='damage_marks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
