# Generated by Django 6.0.4 on 2026-05-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_jobcardinventory_damage_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardinventory',
            name='floor_mat',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='jobcardinventory',
            name='mud_flap',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='jobcardinventory',
            name='wheel_cap',
            field=models.PositiveIntegerField(default=False),
        ),
    ]
