# Generated by Django 6.0.4 on 2026-05-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_jobcardinventory_floor_mat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardinventory',
            name='floor_mat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobcardinventory',
            name='mud_flap',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='jobcardinventory',
            name='wheel_cap',
            field=models.BooleanField(default=False),
        ),
    ]
