# Generated by Django 6.0.4 on 2026-05-15 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_jobcardinventory_floor_mat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcardinventory',
            old_name='mud_flap',
            new_name='accessories',
        ),
        migrations.RenameField(
            model_name='jobcardinventory',
            old_name='floor_mat',
            new_name='center_mirror',
        ),
        migrations.RenameField(
            model_name='jobcardinventory',
            old_name='wheel_cap',
            new_name='frt_wiper',
        ),
        migrations.RemoveField(
            model_name='jobcardinventory',
            name='created_at',
        ),
        migrations.AddField(
            model_name='jobcardinventory',
            name='floor_mat_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcardinventory',
            name='lh_mirror',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardinventory',
            name='mud_flap_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobcardinventory',
            name='rh_mirror',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardinventory',
            name='rr_wiper',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobcardinventory',
            name='wheel_cap_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
