# Generated by Django 6.0.4 on 2026-05-15 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_rename_mud_flap_jobcardinventory_accessories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardTyreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('front_left', 'Front Left'), ('front_right', 'Front Right'), ('rear_left', 'Rear Left'), ('rear_right', 'Rear Right'), ('stepney', 'Stepney')], max_length=30)),
                ('make', models.CharField(blank=True, max_length=50)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('depth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyres', to='core.jobcard')),
            ],
            options={
                'unique_together': {('job', 'position')},
            },
        ),
    ]
