# Generated by Django 6.0.4 on 2026-05-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_jobcardtyreinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcardinventory',
            name='wheel_cap_count',
        ),
        migrations.AddField(
            model_name='jobcardtyreinventory',
            name='wheel_cap_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
