# Generated by Django 6.0.4 on 2026-05-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_remove_jobcardinventory_wheel_cap_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcardtyreinventory',
            name='wheel_cap_count',
        ),
        migrations.AddField(
            model_name='jobcardtyreinventory',
            name='wheel_cap',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
