# Generated by Django 6.0.4 on 2026-05-15 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_jobcardtyreinventory_wheel_cap_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('SMS', 'SMS')], max_length=20)),
                ('mobile_no', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='jobcard_pdfs/')),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('response', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.jobcard')),
            ],
        ),
    ]
