# Generated by Django 6.0.4 on 2026-05-16 14:35

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_communicationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='communicationlog',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.jobcard_pdf_upload_path),
        ),
    ]
