# Generated by Django 6.0.4 on 2026-05-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_stage',
            field=models.IntegerField(choices=[(1, 'Claim Created'), (2, 'Advisor Assigned'), (3, 'Estimate Created'), (4, 'Claim Intimation'), (5, 'Survey'), (6, 'Insurance Approval'), (7, 'Repair Work In Progress'), (8, 'Work Completed'), (9, 'Re Inspection'), (10, 'Liability'), (11, 'Invoiced'), (12, 'Delivery'), (13, 'Closed')], default=1),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Created', max_length=30),
        ),
        migrations.AlterField(
            model_name='claim',
            name='survey_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Re-Inspection', 'Re-Inspection')], default='Open', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobcardassessmentlabour',
            name='decision',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Reject', 'Reject')], default='Approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobcardassessmentpart',
            name='decision',
            field=models.CharField(choices=[('New', 'New'), ('Repair', 'Repair'), ('KO', 'KO'), ('Reject', 'Reject')], default='New', max_length=20),
        ),
    ]
