# Generated by Django 6.0.4 on 2026-05-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_claim_claim_stage_alter_claim_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('Advisor', 'Advisor'), ('MANAGER', 'Manager'), ('Floor Supervisor', 'Floor Supervisor')], default='STAFF', max_length=20),
        ),
    ]
