# Generated by Django 6.0.4 on 2026-05-17 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_employee_employee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allotment_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='core.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='WorkAllocationPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=20)),
                ('picker_name', models.CharField(blank=True, max_length=100)),
                ('pick_from_store', models.BooleanField(default=False)),
                ('eta', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.workallocation')),
                ('job_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobcardpart')),
            ],
        ),
        migrations.CreateModel(
            name='WorkProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Dismantling', 'Damage Body Parts Dismantling'), ('Mechanical', 'Mechanical Work'), ('Repair', 'Body Repairing'), ('Painting', 'Vehicle Painting'), ('Assembly', 'Body Assembling'), ('Fitting', 'Mechanical Fitting')], max_length=30)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('allocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='core.workallocation')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
            ],
        ),
    ]
