# Generated by Django 6.0.4 on 2026-05-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_claim_survey_status_announcement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('Cashless', 'Cashless'), ('NonCashless', 'NonCashless'), ('Paid', 'Paid'), ('Warranty', 'Warranty'), ('FOC', 'FOC')], default='Cashless', max_length=30),
        ),
    ]
