# Generated by Django 6.0.4 on 2026-05-21 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_claim_claim_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardassessmentlabour',
            name='deduction_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
