# Generated by Django 6.0.4 on 2026-05-24 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_align_claim_stage_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='delivered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_claims', to='core.employee'),
        ),
        migrations.AddField(
            model_name='claim',
            name='delivered_to',
            field=models.CharField(blank=True, choices=[('Customer Self', 'Customer Self'), ('Customer Representative', 'Customer Representative'), ('Drop By Driver', 'Drop By Driver')], max_length=40),
        ),
        migrations.AddField(
            model_name='claim',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='delivery_driver_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='delivery_remarks',
            field=models.TextField(blank=True),
        ),
    ]
