# Generated by Django 6.0.4 on 2026-06-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_employee_profile_photo'),
        ('core', '0078_remove_jobcardpart_paint_panel_type'),
    ]

    operations = [
    ]
