# Generated by Codex on 2026-06-03

import django.db.models.deletion
from django.db import migrations, models


def create_default_branch(apps, schema_editor):
    CompanySetup = apps.get_model("core", "CompanySetup")
    Branch = apps.get_model("core", "Branch")
    Employee = apps.get_model("core", "Employee")
    Claim = apps.get_model("core", "Claim")

    company = CompanySetup.objects.first()
    branch, _ = Branch.objects.get_or_create(
        code="HO",
        defaults={
            "parent": company,
            "name": company.company_name if company else "Head Office",
            "address": company.address if company else "",
            "city": company.city if company else "",
            "state": company.state if company else "",
            "pincode": company.pincode if company else "",
            "phone": company.phone if company else "",
            "mobile": company.mobile if company else "",
            "email": company.email if company else "",
            "gst_no": company.gst_no if company else "",
            "is_head_office": True,
            "is_active": True,
        },
    )
    Employee.objects.filter(branch__isnull=True).update(branch=branch)
    Claim.objects.filter(branch__isnull=True).update(branch=branch)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_merge_20260603_0818"),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("pincode", models.CharField(blank=True, max_length=20, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("mobile", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("gst_no", models.CharField(blank=True, max_length=50, null=True)),
                ("is_head_office", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="core.companysetup",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="core.branch",
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claims",
                to="core.branch",
            ),
        ),
        migrations.RunPython(create_default_branch, migrations.RunPython.noop),
    ]
