# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_branch_employee_claim"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="claim_no_alias",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name="branch",
            name="jobcard_no_alias",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
