# Generated by Codex on 2026-06-05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0081_branch_number_aliases"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("STAFF", "Staff"),
                    ("Advisor", "Advisor"),
                    ("MANAGER", "Manager"),
                    ("Floor Supervisor", "Floor Supervisor"),
                    ("Gate Security", "Gate Security"),
                ],
                default="STAFF",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="GateInEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("registration_no", models.CharField(db_index=True, max_length=20)),
                ("current_km", models.PositiveIntegerField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("Service", "Service"),
                            ("Bodyshop", "Bodyshop"),
                            ("Other", "Other"),
                        ],
                        default="Bodyshop",
                        max_length=20,
                    ),
                ),
                ("gate_in_datetime", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Converted", "Converted"),
                            ("Cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gate_in_entries",
                        to="core.branch",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gate_in_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "jobcard",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gate_in_entry",
                        to="core.jobcard",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gate_in_entries",
                        to="core.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-gate_in_datetime"],
                "indexes": [
                    models.Index(fields=["registration_no", "status"], name="core_gatein_registr_6813b3_idx"),
                    models.Index(fields=["service_type", "status"], name="core_gatein_service_f3ef5e_idx"),
                ],
            },
        ),
    ]
