# Generated by Codex on 2026-06-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_gate_in_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("STAFF", "Staff"),
                    ("Advisor", "Advisor"),
                    ("MANAGER", "Manager"),
                    ("Floor Supervisor", "Floor Supervisor"),
                    ("Gate Security", "Gate Security"),
                    ("Reception", "Reception"),
                ],
                default="STAFF",
                max_length=20,
            ),
        ),
    ]
