# Generated by Codex on 2026-06-05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_gate_in_cancel_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="insurance_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="core.insurancecompany",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="policy_no",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="policy_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="policy_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="last_service_km",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="last_service_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="last_service_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
