# Generated by Codex on 2026-06-05

from django.db import migrations, models


def populate_customer_codes(apps, schema_editor):
    Customer = apps.get_model("core", "Customer")

    for customer in Customer.objects.filter(customer_code__isnull=True).order_by("id"):
        customer.customer_code = f"CUST{customer.id:04d}"
        customer.save(update_fields=["customer_code"])


def clear_customer_codes(apps, schema_editor):
    Customer = apps.get_model("core", "Customer")
    Customer.objects.update(customer_code=None)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_vehicle_policy_service_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_code",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[("Individual", "Individual"), ("Corporate", "Corporate")],
                default="Individual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="salutation",
            field=models.CharField(
                blank=True,
                choices=[("Mr", "Mr"), ("Mrs", "Mrs"), ("Ms", "Ms")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="anniversary_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="gst_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="pan_no",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="aadhaar_no",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="alternate_mobile_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="whatsapp_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="preferred_contact_method",
            field=models.CharField(
                choices=[("Mobile", "Mobile"), ("WhatsApp", "WhatsApp"), ("Email", "Email")],
                default="Mobile",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="address_line_1",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="address_line_2",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.CharField(blank=True, default="India", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="company_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="contact_person",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="company_gst_no",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.RunPython(populate_customer_codes, clear_customer_codes),
    ]
