# Generated by Codex on 2026-06-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0086_customer_master_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gateinentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Converted", "Converted"),
                    ("Gate Out", "Gate Out"),
                    ("Cancelled", "Cancelled"),
                ],
                db_index=True,
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="gateinentry",
            name="gate_out_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gate_out_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="gateinentry",
            name="gate_out_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
