# Generated by Django 6.0.4 on 2026-07-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_backfill_user_login_activity'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gateinentry',
            new_name='core_gatein_registr_b74fa9_idx',
            old_name='core_gatein_registr_6813b3_idx',
        ),
        migrations.RenameIndex(
            model_name='gateinentry',
            new_name='core_gatein_service_ab0aa8_idx',
            old_name='core_gatein_service_f3ef5e_idx',
        ),
        migrations.RenameIndex(
            model_name='userloginactivity',
            new_name='core_userlo_user_id_428c35_idx',
            old_name='core_userlo_user_id_44b43b_idx',
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_stage',
            field=models.IntegerField(choices=[(1, 'Claim Created'), (2, 'Advisor Assigned'), (3, 'Estimate Created'), (4, 'Claim Intimation'), (5, 'Survey Done'), (6, 'Insurance Approval'), (7, 'Work Allocation Pending'), (8, 'Repair Work In Progress'), (9, 'Work Completed'), (10, 'Re Inspection'), (11, 'Liability'), (12, 'Invoiced'), (13, 'Delivery'), (14, 'Closed')], default=1),
        ),
    ]
