# Generated by Django 6.0.4 on 2026-07-24 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_dashboard_kpi_function'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardQualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paint_finish', models.BooleanField(default=False)),
                ('color_match', models.BooleanField(default=False)),
                ('panel_alignment', models.BooleanField(default=False)),
                ('electrical_check', models.BooleanField(default=False)),
                ('ac_check', models.BooleanField(default=False)),
                ('road_test', models.BooleanField(default=False)),
                ('washing_done', models.BooleanField(default=False)),
                ('interior_cleaning', models.BooleanField(default=False)),
                ('exterior_cleaning', models.BooleanField(default=False)),
                ('tool_kit_available', models.BooleanField(default=False)),
                ('spare_wheel_available', models.BooleanField(default=False)),
                ('fuel_level_checked', models.BooleanField(default=False)),
                ('customer_belongings_checked', models.BooleanField(default=False)),
                ('documents_checked', models.BooleanField(default=False)),
                ('final_inspection', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, default='')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcard_quality_checks', to=settings.AUTH_USER_MODEL)),
                ('jobcard', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_check', to='core.jobcard')),
            ],
            options={
                'verbose_name': 'Job Card Quality Check',
                'verbose_name_plural': 'Job Card Quality Checks',
                'ordering': ['-updated_at'],
            },
        ),
    ]
