# Generated by Django 6.0.4 on 2026-07-24 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_jobcardqualitycheck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('OK', 'OK'), ('NOT_OK', 'Not OK')], default='PENDING', max_length=10)),
                ('remarks', models.TextField(blank=True, default='')),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quality_check_items_checked', to=settings.AUTH_USER_MODEL)),
                ('quality_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.jobcardqualitycheck')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('quality_check', 'item_key'), name='unique_quality_check_item')],
            },
        ),
    ]
