# Generated by Django 6.0.4

import django.db.models.deletion
from django.db import migrations, models


def create_jobcard_types(apps, schema_editor):
    JobCardType = apps.get_model('core', 'JobCardType')

    types = [
        "Paid",
        "Insurance",
        "Cash",
    ]

    for item in types:
        JobCardType.objects.get_or_create(
            name=item
        )


def migrate_jobcard_values(apps, schema_editor):
    JobCard = apps.get_model('core', 'JobCard')
    JobCardType = apps.get_model('core', 'JobCardType')

    for jobcard in JobCard.objects.all():

        old_value = jobcard.jobcard_type

        if old_value:

            jt, created = JobCardType.objects.get_or_create(
                name=old_value
            )

            jobcard.jobcard_type_new = jt
            jobcard.save(update_fields=['jobcard_type_new'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_gatein_out_km'),
    ]

    operations = [

        migrations.CreateModel(
            name='JobCardType',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('name', models.CharField(
                    max_length=50,
                    unique=True
                )),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Card Type',
                'verbose_name_plural': 'Job Card Types',
                'db_table': 'mst_jobcard_type',
                'ordering': ['display_order', 'name'],
            },
        ),

        migrations.RunPython(
            create_jobcard_types
        ),

        migrations.AddField(
            model_name='jobcard',
            name='jobcard_type_new',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='+',
                to='core.jobcardtype'
            ),
        ),

        migrations.RunPython(
            migrate_jobcard_values
        ),

        migrations.RemoveField(
            model_name='jobcard',
            name='jobcard_type',
        ),

        migrations.RenameField(
            model_name='jobcard',
            old_name='jobcard_type_new',
            new_name='jobcard_type',
        ),
    ]