# Generated by Django 6.0.4 on 2026-07-27 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_jobcardtype_alter_jobcard_jobcard_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jobcardtype',
            table='mst_jobcard_type',
        ),
    ]
