# Generated by Django 6.0.4 on 2026-07-27 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_alter_jobcardtype_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='jobcard_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobcards', to='core.jobcardtype'),
        ),
        migrations.CreateModel(
            name='CustomerApprovalEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('Manual', 'Manual'), ('WhatsApp', 'WhatsApp'), ('SMS', 'SMS'), ('Email', 'Email')], default='Manual', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('message_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_evidence', to='core.jobcard')),
            ],
        ),
    ]
