# Generated by Django 6.0.4 on 2026-07-30 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_alter_jobcard_jobcard_type_customerapprovalevidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardassessmentlabour',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcardassessmentlabour',
            name='assessment_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_jobcard_labours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcardassessmentlabour',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobcardassessmentlabour',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_jobcard_assessment_labours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcardassessmentlabour',
            name='updated_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobcardassessmentpart',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcardassessmentpart',
            name='assessment_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_jobcard_parts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcardassessmentpart',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobcardassessmentpart',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_jobcard_assessment_parts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobcardassessmentpart',
            name='updated_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
