# Generated by Django 6.0.4 on 2026-07-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_jobcardassessmentlabour_approval_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerapprovalevidence',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Need Clarifications', 'Need Clarifications')], default='Pending', max_length=20),
        ),
    ]
