# Generated by Django 6.0.4 on 2026-07-31 01:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_customerapprovalphotoannotation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardDamageAISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('dent', 'Dent'), ('scratch', 'Scratch'), ('broken', 'Broken / cracked'), ('paint', 'Paint damage'), ('missing', 'Missing part'), ('glass', 'Glass damage'), ('other', 'Other')], default='other', max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('x', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('y', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(default='pending_provider', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_ai_suggestions', to='core.jobcard')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_ai_suggestions', to='core.jobcardvehicleconditionphoto')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_damage_ai_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
