# Generated by Django 6.0.4 on 2026-08-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_jobcarddamageaisuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage_type', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('severity', models.CharField(max_length=20)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('approved', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobcard')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobcardvehicleconditionphoto')),
            ],
        ),
        migrations.CreateModel(
            name='JobCardPhotoAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(choices=[('circle', 'Circle'), ('rectangle', 'Rectangle'), ('arrow', 'Arrow'), ('text', 'Text')], max_length=20)),
                ('start_x', models.FloatField(default=0.0)),
                ('start_y', models.FloatField(default=0.0)),
                ('end_x', models.FloatField(blank=True, null=True)),
                ('end_y', models.FloatField(blank=True, null=True)),
                ('text', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#FF0000', max_length=20)),
                ('stroke_width', models.FloatField(default=4.0)),
                ('font_size', models.FloatField(default=18.0)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='core.jobcardvehicleconditionphoto')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
