# Generated by Django 6.0.4 on 2026-08-16 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_jobcarddamage_jobcardphotoannotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('driver_type', models.CharField(choices=[('SELF', 'Self'), ('PAID', 'Paid Driver'), ('RELATIVE', 'Relative')], default='SELF', max_length=20)),
                ('mobile_no', models.CharField(blank=True, max_length=15)),
                ('driving_license_no', models.CharField(max_length=50, unique=True)),
                ('license_valid_until', models.DateField(blank=True, null=True)),
                ('license_document', models.FileField(blank=True, null=True, upload_to='driver_documents/licenses/')),
                ('face_photo', models.ImageField(blank=True, null=True, upload_to='driver_documents/faces/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_policy_document',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_documents/insurance/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rc_document',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_documents/rc/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='primary_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='core.drivermaster'),
        ),
    ]
