# Generated by Django 6.0.4 on 2026-08-16 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_drivermaster_vehicle_insurance_policy_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivermaster',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_master_records', to='core.vehicle'),
        ),
    ]
