# Generated by Django 6.0.4 on 2026-09-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_drivermaster_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_documents/images/'),
        ),
    ]
