# Generated by Django 6.0.4 on 2026-09-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_vehicle_vehicle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='insurance/logos/'),
        ),
    ]
