# Generated by Django 6.0.4 on 2026-09-13 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_insurancecompany_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'Claim Created'), (2, 'Advisor Assigned'), (3, 'Estimate Created'), (4, 'Claim Intimation'), (5, 'Survey Done'), (6, 'Insurance Approval'), (7, 'Work Allocation Pending'), (8, 'Repair Work In Progress'), (9, 'Work Completed'), (10, 'Re Inspection'), (11, 'Liability'), (12, 'Invoiced'), (13, 'Delivery'), (14, 'Closed')])),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.employee')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='core.claim')),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
    ]
