# Generated by Django 6.0.4 on 2026-09-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_claimstagehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='damage_type',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='claim',
            name='recommended_action',
            field=models.CharField(blank=True, default='Approve Repair', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='salvage_applicable',
            field=models.CharField(blank=True, default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='survey_agency',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='claim',
            name='survey_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='claim',
            name='survey_reference_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='survey_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='claim',
            name='survey_type',
            field=models.CharField(blank=True, default='Physical Survey', max_length=50),
        ),
    ]
