# Generated by Django 6.0.4 on 2026-09-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_claim_damage_type_claim_recommended_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='additional_approval_document',
            field=models.FileField(blank=True, null=True, upload_to='claim_approval/'),
        ),
        migrations.AddField(
            model_name='claim',
            name='approval_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='claim',
            name='approval_letter',
            field=models.FileField(blank=True, null=True, upload_to='claim_approval/'),
        ),
        migrations.AddField(
            model_name='claim',
            name='approval_reference_no',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='approval_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='claim',
            name='approval_status',
            field=models.CharField(blank=True, default='Pending', max_length=30),
        ),
        migrations.AddField(
            model_name='claim',
            name='approval_valid_till',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='approved_estimate',
            field=models.FileField(blank=True, null=True, upload_to='claim_approval/'),
        ),
        migrations.AddField(
            model_name='claim',
            name='approved_repair_scope',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='claim',
            name='deductible_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='insurance_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='claim',
            name='internal_remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='claim',
            name='repair_authorization',
            field=models.FileField(blank=True, null=True, upload_to='claim_approval/'),
        ),
    ]
