# Generated by Django 6.0.4 on 2026-09-20 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_claim_additional_approval_document_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qualitycheckitem',
            options={'ordering': ['category_order', 'item_order', 'id']},
        ),
        migrations.AddField(
            model_name='qualitycheckitem',
            name='category_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qualitycheckitem',
            name='item_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qualitycheckitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='qualitycheckitem',
            name='item_key',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qualitycheckitem',
            name='item_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='qualitycheckitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('OK', 'Pass'), ('ATTENTION', 'Attention'), ('NOT_OK', 'Fail'), ('NA', 'N/A')], default='PENDING', max_length=15),
        ),
    ]
