from django.contrib.auth.views import LogoutView
from django.urls import path
from rbac.views import menu_manage, update_user_permission, user_access, user_create
from .views import dashboard, register_view
from . import claim_view, jobcard_views, views
from apps.quality_check import views as quality_check_views
urlpatterns = [
    #path('', dashboard, name='dashboard'),
path('', dashboard, name='dashboard'),
path('dashboard/', dashboard, name='dashboard'),
path('register/', register_view, name='register'),
path("logout/", LogoutView.as_view(next_page="login"), name="logout_view"),
path('insurance/', views.insurance_list, name='insurance'),
path('customer/', views.customer_list, name='customer'),
path('vehicle/', views.vehicle_create, name='vehicle'),
path('vehicle/new/', views.vehicle_create, name='vehicle_new'),
path('driver-master/', views.driver_master, name='driver_master'),
path('ajax/vehicles/', views.vehicle_list_api),
path("ajax/vehicle/<int:pk>/", views.vehicle_detail_api, name="vehicle_detail_api"),
path('ajax/vehicle/<int:pk>/update/', views.vehicle_update_api),
path('ajax/load-variants/', views.load_variants, name='ajax_load_variants'),
path('edit/<int:pk>/', views.insurance_edit, name='insurance_edit'),
path('data/', views.insurance_data),
path('get/<int:pk>/', views.insurance_get),
path('save/', views.insurance_save),
path('ajax/vehicle-search/',views.vehicle_search),
path("ajax/add-vehicle/", views.vehicle_create, name="add_vehicle"),
path('ajax/add-variant/', views.add_variant_ajax, name='add_variant_ajax'),
path('ajax/add-model/', views.add_model_ajax, name='add_model_ajax'),
path('ajax/check-registration/', views.check_registration, name='check_registration'),
path('ajax/vehicle-details/',views.get_vehicle_details,name='vehicle_details'),
path('ajax/vehicle-gate-in-status/', views.vehicle_gate_in_status, name='vehicle_gate_in_status'),
path('ajax/check-customer/', views.check_customer),
path('ajax/customer-search/', views.customer_search),
path('ajax/add-customer/', views.add_customer, name='add_customer'),
path('ajax/customer-details/', views.get_customer_details, name='customer_details'),
path('customer/data/', views.customer_data),
path('customer/get/<int:id>/', views.customer_get),
path('customer/save/', views.customer_save),
path('customer/check-mobile/', views.customer_check_mobile),
path('api/save-columns/', views.save_column_pref),
path('api/load-columns/', views.load_column_pref),
path('surveyor/', views.surveyor_page,name='surveyor'),
path('surveyor/data/', views.surveyor_data),
path('surveyor/save/', views.surveyor_save),
path('surveyor/get/<int:id>/', views.surveyor_get),
path('employee/', views.employee_page,name='employee'),
path('employee/data/', views.employee_data),
path('employee/save/', views.employee_save),
path('employee/get/<int:id>/', views.employee_get),
path('api/claim/', claim_view.claim_list_api),
path('claim/', claim_view.claim_page,name='claim'),
path('claimList/', claim_view.claimList_page,name='claimList'),
path('claim/data/', claim_view.claim_data),
path('claim/save/', claim_view.claim_edit),
path("claim/<int:pk>/edit/",claim_view.claim_edit,name='claim_edit'),
path("ajax/check-open-claim/",claim_view.check_open_claim,name="check_open_claim"),
path("gate-in/", views.gate_in_entry, name="gate_in_entry"),
path("gate-in/data/", views.gate_in_entry_data, name="gate_in_entry_data"),
path("gate-in/export/", views.gate_in_entry_export, name="gate_in_entry_export"),
path("gate-in/<int:pk>/update/", views.gate_in_entry_update, name="gate_in_entry_update"),
path("gate-in/<int:pk>/cancel/", views.gate_in_entry_cancel, name="gate_in_entry_cancel"),
path("gate-in/<int:pk>/gate-out/", views.gate_in_entry_gate_out, name="gate_in_entry_gate_out"),
path('jobCreate/', jobcard_views.jobcard_create, name='jobCreate'),
path('jobCreate/<int:claim_id>/', jobcard_views.jobcard_create, name='jobcard_create_with_claim'),
path('jobcard/<int:pk>/send-paid-approval/', views.send_paid_jobcard_approval, name='send_paid_jobcard_approval'),
path('jobcard/<int:pk>/consent-line-decision/', views.update_customer_consent_line_decision, name='update_customer_consent_line_decision'),
path('jobcard/<int:pk>/approval-evidence/upload/', views.upload_customer_approval_evidence, name='upload_customer_approval_evidence'),
path('jobcard/<int:pk>/approval-annotations/save/', views.save_customer_approval_annotations, name='save_customer_approval_annotations'),
path('jobcard/<int:pk>/damage-ai-suggestions/<int:suggestion_id>/review/', views.review_damage_ai_suggestion, name='review_damage_ai_suggestion'),
path('jobcard/<int:pk>/damage-ai-suggestions/<int:photo_id>/analyze/', views.run_damage_ai_analysis, name='run_damage_ai_analysis'),
path('customer/jobcard-approval/<str:token>/', views.customer_jobcard_approval, name='customer_jobcard_approval'),
path('customer/jobcard-tracking/<str:token>/', views.customer_jobcard_tracking, name='customer_jobcard_tracking'),
path('jobList/', jobcard_views.jobList_page,name='jobList'),
path("api/jobcards/", jobcard_views.jobcard_list_api, name="jobcard_list_api"),
path("jobCard/<int:pk>/edit/",jobcard_views.jobcard_edit,name="jobcard_edit"),
path("jobCard/<int:pk>/second-approval/", jobcard_views.jobcard_second_approval_action, name="jobcard_second_approval_action"),
path('company-setup/', views.company_setup, name='company_setup'),
path("part/", views.upload_itemdata_excel, name="part"),
path("partlist/", views.itemdata_list, name="partlist"),
path("api/part-master/quick-add/", views.part_master_quick_add, name="part_master_quick_add"),
path("api/part-master/search/", views.part_master_search, name="part_master_search"),
path("parts-requisitions/", views.part_requisition_list, name="part_requisition_list"),
path("parts-requisitions/create/", views.part_requisition_create, name="part_requisition_create"),
path("parts-requisitions/job/<int:job_id>/create/", views.create_part_requisition_from_job, name="create_part_requisition_from_job"),
path("parts-requisitions/<int:requisition_id>/", views.part_requisition_detail, name="part_requisition_detail"),
path("parts-requisitions/<int:requisition_id>/print/", views.part_requisition_print, name="part_requisition_print"),
path("parts-manager/", views.parts_manager_dashboard, name="parts_manager_dashboard"),
path("part-orders/", views.part_order_list, name="part_order_list"),
path("part_order_create/", views.part_order_create, name="part_order_create"),
path("part-orders/<int:header_id>/edit/", views.part_order_header_edit, name="part_order_header_edit"),
path("part-orders/<int:header_id>/print/", views.part_order_print, name="part_order_print"),
path("part-orders/job/<int:job_id>/create/", views.create_part_order_from_job, name="create_part_order_from_job"),
path("part-orders/job/<int:job_id>/", views.part_order_job_detail, name="part_order_job_detail"),
path("api/part-orders/jobs/", views.part_order_jobs_api, name="part_order_jobs_api"),
path("api/part-orders/headers/", views.part_order_headers_api, name="part_order_headers_api"),
path("api/part-orders/job/<int:job_id>/headers/", views.part_order_job_headers_api, name="part_order_job_headers_api"),
path("api/part-orders/job/<int:job_id>/", views.part_order_job_orders_api, name="part_order_job_orders_api"),
path("api/part-orders/header/<int:header_id>/lines/", views.part_order_header_lines_api, name="part_order_header_lines_api"),
path("api/part-orders/line/<int:order_id>/update/", views.update_part_order_line_api, name="update_part_order_line_api"),
path("api/part-orders/line/<int:order_id>/delete/", views.delete_part_order_line_api, name="delete_part_order_line_api"),
path("api/jobcard/<int:job_id>/assessment/", jobcard_views.jobcard_assessment_api,name="jobcard_assessment_api"),
path("api/jobcard/<int:job_id>/assessment/save/",jobcard_views.save_jobcard_assessment,name="save_jobcard_assessment"),
path("jobCard/<int:pk>/assessment-print/", jobcard_views.assessment_print, name="assessment_print"),
path("jobCard/<int:job_id>/vehicle-condition-photos/", jobcard_views.vehicle_condition_photo_view, name="vehicle_condition_photo_view"),
path("jobCard/<int:job_id>/vehicle-condition-photos/download/", jobcard_views.download_vehicle_condition_photos, name="download_vehicle_condition_photos"),
path("ajax/part-lookup/", views.part_lookup, name="part_lookup"),
path("jobCard/<int:pk>/print-preview/<str:token>/",jobcard_views.jobcard_print_preview,name="jobcard_print_preview"),
path( "jobCard/<int:pk>/print/<str:token>/", jobcard_views.jobcard_print_pdf,name="jobcard_print"),
path("jobCard/<int:pk>/estimate-print/", jobcard_views.estimate_print, name="estimate_print"),
path("whatsapp_text_link/<int:pk>/", jobcard_views.whatsapp_text_link,name="whatsapp_text_link"),
path("whatsapp-cloud-test/", jobcard_views.whatsapp_cloud_test, name="whatsapp_cloud_test"),
path("ajax/unread-notifications/",views.unread_notifications,name="unread_notifications"),
path("ajax/notification/<int:pk>/read/",views.mark_notification_read,name="mark_notification_read"),
path("ajax/notifications/read-all/",views.mark_all_notifications_read,name="mark_all_notifications_read"),
path("work-allocation/",views.work_allocation_list,name="work_allocation_list"),
path("bodyshop-control/", views.bodyshop_control_menu, name="bodyshop_control_menu"),
path("bodyshop-control-board/", views.bodyshop_control_board, name="bodyshop_control_board"),
path("reports/workshop/daily-in-out/", views.daily_in_out_report, name="daily_in_out_report"),
path("reports/dashboard/kpi-cards/", views.kpi_cards_report, name="kpi_cards_report"),
path("reports/tat/summary/", views.tat_summary_report, name="tat_summary_report"),
path("reports/insurance/surveyor-performance/", views.surveyor_performance_report, name="surveyor_performance_report"),
path("reports/<path:report_key>/", views.report_placeholder, name="report_placeholder"),
path("workshop-resource/", views.workshop_resource_view, name="workshop_resource"),
path("my-work/", views.my_work_list, name="my_work_list"),
path("my-work/<int:progress_id>/action/", views.my_work_action, name="my_work_action"),
path("work-allocation/<int:job_id>/completion-report/", views.work_completion_report, name="work_completion_report"),
path("work-allocation/progress/<int:progress_id>/photos/", views.work_progress_photo_view, name="work_progress_photo_view"),
path("work-allocation/<int:job_id>/reinspection-photos/", views.reinspection_photo_view, name="reinspection_photo_view"),
path("work-allocation/<int:job_id>/reinspection-photos/download/", views.download_reinspection_photos, name="download_reinspection_photos"),
path("work-allocation/<int:job_id>/reinspection-photos/<int:photo_id>/delete/", views.delete_reinspection_photo, name="delete_reinspection_photo"),
path("work-allocation/<int:job_id>/",views.work_allocation_entry,name="work_allocation_entry"),
path("ajax/work-allocation/check-employee/", views.check_work_allocation_employee, name="check_work_allocation_employee"),
path("ajax/advisor-workload/", claim_view.advisor_workload_api, name="advisor_workload_api"),
path("ajax/unread-announcements/",views.unread_announcements,name="unread_announcements"),
path("ajax/announcement/<int:pk>/read/",views.mark_announcement_read,name="mark_announcement_read"),
path("user-create/",user_create,name="user_create"),
path("user-access/",user_access,name="user_access"),
path("menu-manage/",menu_manage,name="menu_manage"),
path("update-user-permission/",update_user_permission,name="update_user_permission"),
path("login-activity/", views.login_activity_page, name="login_activity"),
path("jobcard/<int:jobcard_id>/jasper-print/",jobcard_views.print_jobcard_jasper,name="print_jobcard_jasper"),
path(
    "jobCard/<int:jobcard_id>/quality-check/",
    quality_check_views.quality_check_detail,
    name="quality_check_detail",
),
path(
    "quality-inspector/",
    quality_check_views.quality_inspector_dashboard,
    name="quality_inspector_dashboard",
),
path(
    "jobCard/<int:jobcard_id>/quality-check/report/",
    quality_check_views.quality_check_report,
    name="quality_check_report",
),
path(
    "ajax/vehicle-form-options/",
    views.vehicle_form_options_api,
    name="vehicle_form_options",
),
path(
    "ajax/vehicle-form-data/",
    views.vehicle_form_data_api,
    name="vehicle_form_data",
),

path("vehicle/<int:pk>/edit/", views.vehicle_edit_page, name="vehicle_edit"),
path('ajax/driver-master/', views.driver_master_data_api, name='driver_master_data_api'),
path('ajax/driver-master/save/', views.driver_master_save_api, name='driver_master_save_api'),
path('ajax/driver-master/<int:pk>/', views.driver_master_get_api, name='driver_master_get_api'),
path(
    "ajax/react-menu/",
    views.react_menu_api,
    name="react_menu_api",
),
path(
    "ajax/dashboard-data/",
    views.dashboard_data,
    name="dashboard_data",
),
path(
    "ajax/advisor-dashboard-data/",
    views.advisor_dashboard_data,
    name="advisor_dashboard_data"
),
path(
    "ajax/header-data/",
    views.header_data,
    name="header_data"
),
path(
    "ajax/dashboard-branches/",
    views.dashboard_branches,
    name="dashboard_branches",
),
]
