from django.contrib.auth.views import LogoutView
from django.urls import path

import rbac
from rbac.views import menu_manage, update_user_permission, user_access, user_create
from .views import dashboard, register_view
from . import views
urlpatterns = [
    #path('', dashboard, name='dashboard'),
path('', dashboard, name='dashboard'),
path('dashboard/', dashboard, name='dashboard'),
path('register/', register_view, name='register'),
path("logout/", LogoutView.as_view(next_page="login"), name="logout_view"),
path('insurance/', views.insurance_list, name='insurance'),
path('customer/', views.customer_list, name='customer'),
path('vehicle/', views.vehicle_create, name='vehicle'),
path('ajax/vehicles/', views.vehicle_list_api),
path("ajax/vehicle/<int:pk>/", views.vehicle_detail_api, name="vehicle_detail_api"),
path('ajax/vehicle/<int:pk>/update/', views.vehicle_update_api),
path('ajax/load-variants/', views.load_variants, name='ajax_load_variants'),
path('edit/<int:pk>/', views.insurance_edit, name='insurance_edit'),
path('data/', views.insurance_data),
path('get/<int:pk>/', views.insurance_get),
path('save/', views.insurance_save),
path('ajax/vehicle-search/',views.vehicle_search),
path("ajax/add-vehicle/", views.vehicle_create, name="add_vehicle"),
path('ajax/add-variant/', views.add_variant_ajax, name='add_variant_ajax'),
path('ajax/add-model/', views.add_model_ajax, name='add_model_ajax'),
path('ajax/check-registration/', views.check_registration, name='check_registration'),
path('ajax/vehicle-details/',views.get_vehicle_details,name='vehicle_details'),
path('ajax/check-customer/', views.check_customer),
path('ajax/customer-search/', views.customer_search),
path('ajax/add-customer/', views.add_customer, name='add_customer'),
path('ajax/customer-details/', views.get_customer_details, name='customer_details'),
path('customer/data/', views.customer_data),
path('customer/get/<int:id>/', views.customer_get),
path('customer/save/', views.customer_save),
path('api/save-columns/', views.save_column_pref),
path('api/load-columns/', views.load_column_pref),
path('surveyor/', views.surveyor_page,name='surveyor'),
path('surveyor/data/', views.surveyor_data),
path('surveyor/save/', views.surveyor_save),
path('surveyor/get/<int:id>/', views.surveyor_get),
path('employee/', views.employee_page,name='employee'),
path('employee/data/', views.employee_data),
path('employee/save/', views.employee_save),
path('employee/get/<int:id>/', views.employee_get),
path('api/claim/', views.claim_list_api),
path('claim/', views.claim_page,name='claim'),
path('claimList/', views.claimList_page,name='claimList'),
path('claim/data/', views.claim_data),
path('claim/save/', views.claim_edit),
path("claim/<int:pk>/edit/",views.claim_edit,name='claim_edit'),
path("ajax/check-open-claim/",views.check_open_claim,name="check_open_claim"),
path('jobCreate/', views.jobcard_create, name='jobCreate'),
path('jobCreate/<int:claim_id>/', views.jobcard_create, name='jobcard_create_with_claim'),
path('jobList/', views.jobList_page,name='jobList'),
path("api/jobcards/", views.jobcard_list_api, name="jobcard_list_api"),
path("jobCard/<int:pk>/edit/",views.jobcard_edit,name="jobcard_edit"),
path('company-setup/', views.company_setup, name='company_setup'),
path("part/", views.upload_itemdata_excel, name="part"),
path("partlist/", views.itemdata_list, name="partlist"),
path("part-orders/", views.part_order_list, name="part_order_list"),
path("part_order_create/", views.part_order_create, name="part_order_create"),
path("part-orders/<int:header_id>/print/", views.part_order_print, name="part_order_print"),
path("part-orders/job/<int:job_id>/create/", views.create_part_order_from_job, name="create_part_order_from_job"),
path("part-orders/job/<int:job_id>/", views.part_order_job_detail, name="part_order_job_detail"),
path("api/part-orders/jobs/", views.part_order_jobs_api, name="part_order_jobs_api"),
path("api/part-orders/headers/", views.part_order_headers_api, name="part_order_headers_api"),
path("api/part-orders/job/<int:job_id>/headers/", views.part_order_job_headers_api, name="part_order_job_headers_api"),
path("api/part-orders/job/<int:job_id>/", views.part_order_job_orders_api, name="part_order_job_orders_api"),
path("api/part-orders/header/<int:header_id>/lines/", views.part_order_header_lines_api, name="part_order_header_lines_api"),
path("api/part-orders/line/<int:order_id>/update/", views.update_part_order_line_api, name="update_part_order_line_api"),
path("api/part-orders/line/<int:order_id>/delete/", views.delete_part_order_line_api, name="delete_part_order_line_api"),
path("api/jobcard/<int:job_id>/assessment/", views.jobcard_assessment_api,name="jobcard_assessment_api"),
path("api/jobcard/<int:job_id>/assessment/save/",views.save_jobcard_assessment,name="save_jobcard_assessment"),
path("jobCard/<int:pk>/assessment-print/", views.assessment_print, name="assessment_print"),
path("jobCard/<int:job_id>/vehicle-condition-photos/", views.vehicle_condition_photo_view, name="vehicle_condition_photo_view"),
path("jobCard/<int:job_id>/vehicle-condition-photos/download/", views.download_vehicle_condition_photos, name="download_vehicle_condition_photos"),
path("ajax/part-lookup/", views.part_lookup, name="part_lookup"),
path("jobCard/<int:pk>/print-preview/<str:token>/",views.jobcard_print_preview,name="jobcard_print_preview"),
path( "jobCard/<int:pk>/print/<str:token>/", views.jobcard_print_pdf,name="jobcard_print"),
path("jobCard/<int:pk>/estimate-print/", views.estimate_print, name="estimate_print"),
path("whatsapp_text_link/<int:pk>/", views.whatsapp_text_link,name="whatsapp_text_link"),
path("ajax/unread-notifications/",views.unread_notifications,name="unread_notifications"),
path("ajax/notification/<int:pk>/read/",views.mark_notification_read,name="mark_notification_read"),
path("work-allocation/",views.work_allocation_list,name="work_allocation_list"),
path("my-work/", views.my_work_list, name="my_work_list"),
path("my-work/<int:progress_id>/action/", views.my_work_action, name="my_work_action"),
path("work-allocation/<int:job_id>/completion-report/", views.work_completion_report, name="work_completion_report"),
path("work-allocation/progress/<int:progress_id>/photos/", views.work_progress_photo_view, name="work_progress_photo_view"),
path("work-allocation/<int:job_id>/reinspection-photos/", views.reinspection_photo_view, name="reinspection_photo_view"),
path("work-allocation/<int:job_id>/reinspection-photos/download/", views.download_reinspection_photos, name="download_reinspection_photos"),
path("work-allocation/<int:job_id>/reinspection-photos/<int:photo_id>/delete/", views.delete_reinspection_photo, name="delete_reinspection_photo"),
path("work-allocation/<int:job_id>/",views.work_allocation_entry,name="work_allocation_entry"),
path("ajax/work-allocation/check-employee/", views.check_work_allocation_employee, name="check_work_allocation_employee"),
path("ajax/unread-announcements/",views.unread_announcements,name="unread_announcements"),
path("ajax/announcement/<int:pk>/read/",views.mark_announcement_read,name="mark_announcement_read"),
path("user-create/",user_create,name="user_create"),
path("user-access/",user_access,name="user_access"),
path("menu-manage/",menu_manage,name="menu_manage"),
path("update-user-permission/",update_user_permission,name="update_user_permission"),
]
