# Generated by Django 6.0.4 on 2026-05-03 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='icon',
        ),
        migrations.AddField(
            model_name='menu',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='url_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
